sudo: false

language: minimal

deploy:
  - provider: script
    skip_cleanup: true
    script: sh deploy.sh
    on:
      branch: master

before_install:
- openssl aes-256-cbc -K $encrypted_9595d4ecd153_key -iv $encrypted_9595d4ecd153_iv
  -in deploy_key.enc -out ./deploy_key -d
